const diceBag = {
  fourByFOurDice: [
    "AAEEGN",
    "ABBJOO",
    "ACHOPS",
    "AFFKPS",
    "AOOTTW",
    "CIMOTU",
    "DEILRX",
    "DELRVY",
    "DISTTY",
    "EEGHNW",
    "EEINSU",
    "EHRTVW",
    "EIOSST",
    "ELRTTY",
    "HIMNUQu",
    "HLNNRZ"
  ],
  fiveByFiveDice: [
    "AAAFRS",
    "AAEEEE",
    "AAFIRS",
    "ADENNN",
    "AEEEEM",
    "AEEGMU",
    "AEGMNN",
    "AFIRSY",
    "BBJKXZ",
    "CCENST",
    "EIILST",
    "CEIPST",
    "DDHNOT",
    "DHHLOR",
    "DHHNOW",
    "DHLNOR",
    "EIIITT",
    "EILPST",
    "EMOTTT",
    "ENSSSU",
    "FIPRSY", // Alternate cube is: Qu-In-Th-Er-He-An
    "GORRVW",
    "IPRSYY",
    "NOOTUW",
    "OOOTTU"
  ],
  sixBySixDice: [
    "AAAFRS",
    "AAEEEE",
    "AAEEOO",
    "AAFIRS",
    "ABDEIO",
    "ADENNN",
    "AEEEEM",
    "AEEGMU",
    "AEGMNN",
    "AEILMN",
    "AEINOU",
    "AFIRSY",
    "AEHIQT", // Should be 'AnErHeInQuTh'
    "BBJKXZ",
    "CCENST",
    "CDDLNN",
    "CEIITT",
    "CEIPST",
    "CFGNUY",
    "DDHNOT",
    "DHHLOR",
    "DHHNOW",
    "DHLNOR",
    "EHILRS",
    "EIILST",
    "EILPST",
    "EIO###",
    "EMTTTO",
    "ENSSSU",
    "GORRVW",
    "HIRSTV",
    "HOPRST",
    "IPRSYY",
    "JKQuWXZ",
    "NOOTUW",
    "OOOTTU"
  ]
};

export default diceBag;
